### PR TITLE
tweak readme to include bower step

### PR DESCRIPTION
**Pull request by tphyahoo**

### CODE REVIEW

**Comment by FranklinChen** [comment]
I'm on Mac and noticed `npm install` still fails because `pulp install` fails.

**Comment by bodil** [comment]
Would recommend filing an issue on the Pulp repo if so. I haven't owned an Apple computer since about 1985, though, so it might need to be accompanied by a PR. :)

**Comment by davidhq** [comment]
I also see the same issues: https://gist.github.com/davidhq/fa04f2cd32c7510a0e02

when I run `bower install`, it seems to work...

then `npm start` also works but I get this in the console: 

```
Server running at http://localhost:1337/ [root: /Users/david/Projects/playground/purescript-is-magic, fallback: /Users/david/Projects/playground/purescript-is-magic/index.html]
* Browserifying project in /Users/david/Projects/playground/purescript-is-magic
* Building project in /Users/david/Projects/playground/purescript-is-magic
* ERROR: Node executable not found.
```

Game shows only background and this JS error: `Uncaught SyntaxError: Unexpected token <`

Any idea how to solve this `Node executable not found` error first?

**Comment by bodil** [comment]
Oh, wow. I've just realised that the install step runs `pulp install`, which is a nonexistent command, not `pulp dep install`. That explains what's going wrong here, I guess. :)

I'm updating this for 0.7 and will include a fix for this in the update.

**Pull request closed without merging**
